// code generated by thespian; DO NOT EDIT

package ticker

import (
	"github.com/djmitche/thespian"
	import1 "github.com/djmitche/thespian/mailbox"
)

// tickerBase is embedded in the private actor struct and contains
// common fields as well as default method implementations
type tickerBase struct {
	rt *thespian.Runtime
	tx *TickerTx
	rx *TickerRx
}

// handleStart is called when the actor starts.  The default implementation
// does nothing, but users may implement this method to perform startup.
func (a *tickerBase) handleStart() {}

// handleStop is called when the actor stops cleanly.  The default
// implementation does nothing, but users may implement this method to perform
// cleanup.
func (a *tickerBase) handleStop() {}

// handleSuperEvent is called for supervisory events.  Actors which do not
// supervise need not implement this method.
func (a *tickerBase) handleSuperEvent(ev thespian.SuperEvent) {}

// TickerBuilder is used to build new Ticker actors.
type TickerBuilder struct {
	ticker
}

func (bldr TickerBuilder) spawn(rt *thespian.Runtime) *TickerTx {
	reg := rt.Register()

	rx := &TickerRx{
		id:         reg.ID,
		rt:         rt,
		stopChan:   reg.StopChan,
		superChan:  reg.SuperChan,
		healthChan: reg.HealthChan,
		tkr:        import1.NewTickerRx(rt),
	}

	tx := &TickerTx{
		ID:       reg.ID,
		stopChan: reg.StopChan,
	}

	// copy to a new ticker instance
	pvt := bldr.ticker
	pvt.rt = rt
	pvt.rx = rx
	pvt.tx = tx

	go pvt.loop()
	return tx
}

// TickerRx contains the Rx sides of the mailboxes, for access from the
// Ticker implementation.
type TickerRx struct {
	id uint64
	rt *thespian.Runtime

	stopChan   <-chan struct{}
	superChan  <-chan thespian.SuperEvent
	healthChan <-chan struct{}
	tkr        import1.TickerRx
}

// supervise starts supervision of the actor identified by otherID.
// It is a shortcut to thespian.Runtime.Supervize.
func (rx *TickerRx) supervise(otherID uint64) {
	rx.rt.Supervise(rx.id, otherID)
}

// unsupervise stops supervision of the actor identified by otherID.
// It is a shortcut to thespian.Runtime.Unupervize.
func (rx *TickerRx) unsupervise(otherID uint64) {
	rx.rt.Unsupervise(rx.id, otherID)
}

// TickerTx is the public handle for Ticker actors.
type TickerTx struct {
	// ID is the unique ID of this actor
	ID       uint64
	stopChan chan<- struct{}
}

// Stop sends a message to stop the actor.  This does not wait until
// the actor has stopped.
func (a *TickerTx) Stop() {
	select {
	case a.stopChan <- struct{}{}:
	default:
	}
}

func (a *ticker) loop() {
	rx := a.rx
	defer func() {
		rx.tkr.Stop()
		a.rt.ActorStopped(a.rx.id)
	}()
	a.handleStart()
	for {
		select {
		case <-rx.healthChan:
			// nothing to do
		case ev := <-rx.superChan:
			a.handleSuperEvent(ev)
		case <-rx.stopChan:
			a.handleStop()
			return
		case t := <-rx.tkr.Chan():
			a.handleTkr(t)
		}
	}
}
