// code generated by thespian; DO NOT EDIT

package gentest

import (
	"github.com/djmitche/thespian"
)

// concatenatorBase is embedded in the private actor struct and contains
// common fields as well as default method implementations
type concatenatorBase struct {
	rt *thespian.Runtime
	tx *ConcatenatorTx
	rx *ConcatenatorRx
}

// handleStart is called when the actor starts.  The default implementation
// does nothing, but users may implement this method to perform startup.
func (a *concatenatorBase) handleStart() {}

// handleStop is called when the actor stops cleanly.  The default
// implementation does nothing, but users may implement this method to perform
// cleanup.
func (a *concatenatorBase) handleStop() {}

// handleSuperEvent is called for supervisory events.  Actors which do not
// supervise need not implement this method.
func (a *concatenatorBase) handleSuperEvent(ev thespian.SuperEvent) {}

// ConcatenatorBuilder is used to build new Concatenator actors.
type ConcatenatorBuilder struct {
	concatenator
	input  StringMailbox
	output StringChanMailbox
}

func (bldr ConcatenatorBuilder) spawn(rt *thespian.Runtime) *ConcatenatorTx {
	reg := rt.Register()
	bldr.input.ApplyDefaults()
	bldr.output.ApplyDefaults()

	rx := &ConcatenatorRx{
		id:         reg.ID,
		rt:         rt,
		stopChan:   reg.StopChan,
		superChan:  reg.SuperChan,
		healthChan: reg.HealthChan,
		input:      bldr.input.Rx(),
		output:     bldr.output.Rx(),
	}

	tx := &ConcatenatorTx{
		ID:       reg.ID,
		stopChan: reg.StopChan,
		input:    bldr.input.Tx(),
		output:   bldr.output.Tx(),
	}

	// copy to a new concatenator instance
	pvt := bldr.concatenator
	pvt.rt = rt
	pvt.rx = rx
	pvt.tx = tx

	go pvt.loop()
	return tx
}

// ConcatenatorRx contains the Rx sides of the mailboxes, for access from the
// Concatenator implementation.
type ConcatenatorRx struct {
	id uint64
	rt *thespian.Runtime

	stopChan   <-chan struct{}
	superChan  <-chan thespian.SuperEvent
	healthChan <-chan struct{}
	input      StringRx
	output     StringChanRx
}

// supervise starts supervision of the actor identified by otherID.
// It is a shortcut to thespian.Runtime.Supervize.
func (rx *ConcatenatorRx) supervise(otherID uint64) {
	rx.rt.Supervise(rx.id, otherID)
}

// unsupervise stops supervision of the actor identified by otherID.
// It is a shortcut to thespian.Runtime.Unupervize.
func (rx *ConcatenatorRx) unsupervise(otherID uint64) {
	rx.rt.Unsupervise(rx.id, otherID)
}

// ConcatenatorTx is the public handle for Concatenator actors.
type ConcatenatorTx struct {
	// ID is the unique ID of this actor
	ID       uint64
	stopChan chan<- struct{}
	input    StringTx
	output   StringChanTx
}

// Stop sends a message to stop the actor.  This does not wait until
// the actor has stopped.
func (a *ConcatenatorTx) Stop() {
	select {
	case a.stopChan <- struct{}{}:
	default:
	}
}

// Input sends to the actor's input mailbox.
func (tx *ConcatenatorTx) Input(m string) {
	tx.input.C <- m
}

// Output sends to the actor's output mailbox.
func (tx *ConcatenatorTx) Output(m chan<- string) {
	tx.output.C <- m
}

func (a *concatenator) loop() {
	rx := a.rx
	defer func() {

		a.rt.ActorStopped(a.rx.id)
	}()
	a.handleStart()
	for {
		select {
		case <-rx.healthChan:
			// nothing to do
		case ev := <-rx.superChan:
			a.handleSuperEvent(ev)
		case <-rx.stopChan:
			a.handleStop()
			return
		case m := <-rx.input.C:
			a.handleInput(m)
		case m := <-rx.output.C:
			a.handleOutput(m)
		}
	}
}
