// code generated by thespian; DO NOT EDIT

package gentest

// StringMailbox is a mailbox for messages of type string.
type StringMailbox struct {
	C chan string
}

// ApplyDefaults applies default settings to this String, if
// the struct has its zero value.
func (mbox *StringMailbox) ApplyDefaults() {
	if mbox.C == nil {
		mbox.C = make(chan string, 10) // default channel size
	}
}

// Tx creates a StringTx for this mailbox
func (mbox *StringMailbox) Tx() StringTx {
	return StringTx{
		C: mbox.C,
	}
}

// Rx creates a StringRx for this mailbox
func (mbox *StringMailbox) Rx() StringRx {
	return StringRx{
		C: mbox.C,
	}
}

// StringTx sends to a mailbox for messages of type string.
type StringTx struct {
	C chan<- string
}

// StringRx receives from a mailbox for messages of type string.
type StringRx struct {
	C <-chan string
}
