// code generated by thespian; DO NOT EDIT

package gentest

// StringChanMailbox is a mailbox for messages of type chan<- string.
type StringChanMailbox struct {
	C chan chan<- string
}

// ApplyDefaults applies default settings to this StringChan, if
// the struct has its zero value.
func (mbox *StringChanMailbox) ApplyDefaults() {
	if mbox.C == nil {
		mbox.C = make(chan chan<- string, 10) // default channel size
	}
}

// Tx creates a StringChanTx for this mailbox
func (mbox *StringChanMailbox) Tx() StringChanTx {
	return StringChanTx{
		C: mbox.C,
	}
}

// Rx creates a StringChanRx for this mailbox
func (mbox *StringChanMailbox) Rx() StringChanRx {
	return StringChanRx{
		C: mbox.C,
	}
}

// StringChanTx sends to a mailbox for messages of type chan<- string.
type StringChanTx struct {
	C chan<- chan<- string
}

// StringChanRx receives from a mailbox for messages of type chan<- string.
type StringChanRx struct {
	C <-chan chan<- string
}
