// code generated by thespian; DO NOT EDIT

package super

import (
	"github.com/djmitche/thespian"
)

// SuperviseeBuilder is used to buidl new Supervisee actors.
type SuperviseeBuilder struct {
	supervisee
}

func (bldr SuperviseeBuilder) spawn(rt *thespian.Runtime) *SuperviseeTx {
	reg := rt.Register()

	rx := &SuperviseeRx{
		id:         reg.ID,
		rt:         rt,
		stopChan:   reg.StopChan,
		superChan:  reg.SuperChan,
		healthChan: reg.HealthChan,
	}

	tx := &SuperviseeTx{
		ID:       reg.ID,
		stopChan: reg.StopChan,
	}

	// copy to a new supervisee instance
	pvt := bldr.supervisee
	pvt.rt = rt
	pvt.rx = rx
	pvt.tx = tx

	go pvt.loop()
	return tx
}

// SuperviseeRx contains the Rx sides of the mailboxes, for access from the
// Supervisee implementation.
type SuperviseeRx struct {
	id uint64
	rt *thespian.Runtime

	stopChan   <-chan struct{}
	superChan  <-chan thespian.SuperEvent
	healthChan <-chan struct{}
}

// supervise starts supervision of the actor identified by otherID.
// It is a shortcut to thespian.Runtime.Supervize.
func (rx *SuperviseeRx) supervise(otherID uint64) {
	rx.rt.Supervise(rx.id, otherID)
}

// unsupervise stops supervision of the actor identified by otherID.
// It is a shortcut to thespian.Runtime.Unupervize.
func (rx *SuperviseeRx) unsupervise(otherID uint64) {
	rx.rt.Unsupervise(rx.id, otherID)
}

// SuperviseeTx is the public handle for Supervisee actors.
type SuperviseeTx struct {
	// ID is the unique ID of this actor
	ID       uint64
	stopChan chan<- struct{}
}

// Stop sends a message to stop the actor.  This does not wait until
// the actor has stopped.
func (a *SuperviseeTx) Stop() {
	select {
	case a.stopChan <- struct{}{}:
	default:
	}
}

func (a *supervisee) loop() {
	rx := a.rx
	defer func() {
		a.rt.ActorStopped(a.rx.id)
	}()
	a.handleStart()
	for {
		select {
		case <-rx.healthChan:
			// nothing to do
		case ev := <-rx.superChan:
			a.handleSuperEvent(ev)
		case <-rx.stopChan:
			a.handleStop()
			return
		}
	}
}
