// code generated by thespian; DO NOT EDIT

package mailbox

import (
	"github.com/benbjohnson/clock"
	"github.com/djmitche/thespian"
	"time"
)

// TickerRx contains a ticker that the actor implementation can control
type TickerRx struct {
	// ticker is the ticker this mailbox responds to, or nil if it is disabled
	ticker *clock.Ticker
	clock  clock.Clock
}

func NewTickerRx(rt *thespian.Runtime) TickerRx {
	return TickerRx{
		ticker: nil,
		clock:  rt.Clock,
	}
}

// Chan gets a channel for this ticker, or nil if the ticker is not started.
func (rx *TickerRx) Chan() <-chan time.Time {
	if rx.ticker == nil {
		return nil
	}
	return rx.ticker.C
}

// Reset stops a ticker and resets its period to the specified duration.
func (rx *TickerRx) Reset(d time.Duration) {
	if rx.ticker == nil {
		rx.ticker = rx.clock.Ticker(d)
	} else {
		rx.ticker.Reset(d)
	}
}

// Stop stops this ticker.  This is called automatically on agent stop.
func (rx *TickerRx) Stop() {
	if rx.ticker != nil {
		rx.ticker.Stop()
	}
}
